### ISSUE TITLE
Create Hacker Registration Flow

### ISSUE THREAD

**Issue by xxzbuckxx** [CruzHacks/cruzhacks-2024-website#18]
# Scope

Branch: `feature/hacker-applications`
Also use: cruzhacks-2024-backend repo `feature/hacker-applications`

Create the user registration flow  as [detailed by the Figma Mockup](https://www.figma.com/file/IXAajiFoWwcPU70DFs6hRt/Site-Architecture?type=design&node-id=0%3A1&mode=design&t=Q1eT9Z2RuCF6PYwa-1).

Components to mockup the registration are displayed at the apply route (`src/views/apply/index.tsx`). Routing is already implemented for the application so go to BASE_URL/apply in your browser to test / view the component.

There are 4 sections as follows:

1. Demographics
2. Short Response
3. Logistics
4. Socials

Each form section has a schema that can be used for validation as listed in `src/utils/types.ts`. The form is submitted all at once combining the individual section schemas into a final `ApplicationSchema`. I implemented a backend endpoint already to submit an application as well as sample frontend code to see how this is done. To test this make sure to pull the backend and checkout branch `features/hacker-applications` and start the local emulators.

## Additional notes:

For section 1 - demographics, make sure to check Firebase to see if the supplied email and supplied phone number are unique. Sadly there is no frontend function for this, so there are 2 possible solutions:

**Solution 1:**

Make a backend function in the `cruzhacks-2024-backend` repo (in the `auth.tsx` controller) to verify if email and phone number are unique. I think you should be using the Zod validator to call the backend endpoint and display an error notification using `react-hot-toast` (e.g. `toast.error(errorMessage)`. However, you may just throw an error on submit, not sure exactly the best way atm you can probably do some googling to figure that out.

**Solution 2:**
An alternative approach is to just create an account at this step because firebase will tell you if the supplied credentials are unique. This is good because it reduces the number of API calls (although I don't see us going over the free tier so not a big concern). The problem with this approach is the password enter is on the next page, making the account creation span 2 pages. I think it is kind of annoying to have an error popup saying you have to go back a page to enter a unique email / phone number but its not the end of the world.

## TODO:

- [ ] Address unique email / phone number issue
- [ ] Implement Progress bar wrapper component
- [ ] Implement Form sections:
    - [ ] Section 1 - Demographics
    - [ ] Section 2 - Short Response
    - [ ] Section 3 - Logistics
    - [ ] Section 4 - Socials
- [ ] Implement submit
