### ISSUE TITLE
Create Hacker Application Form Frontend Component

### ISSUE THREAD

**Issue by xxzbuckxx** [CruzHacks/cruzhacks-2024-website#4]
Based on [last year's hackathon submission form](https://docs.google.com/forms/d/1qtk6kBBq6jZ9rprDl-U_4Pvl5vhJ30PH2B759A-xA1k/edit) we will have a form element using react-hook-form that applicants can fillout in order to apply to the hackathon.

Additionally, remember to add headings/titles/sections as corresponding with the google form from last year (linked above).

## TODO:

- [x] Create Application.tsx component
- [ ] Complete `applicationSchema` to validate data strictly (in accordance to last years google form)
    - [ ] Create any necessary enums
- [ ] Create sections and headings for the various questions / sections on the form
- [ ] Find APIs  (or use another method) for form entries like country and school
- [ ] Implement form entries (copy and adjust given first name element)
