### ISSUE TITLE
Style Login and Signup according to Figma

### ISSUE THREAD

**Issue by xxzbuckxx** [CruzHacks/cruzhacks-2024-website#6]
# Scope

The login and signup have good validation and error messages ! Yay! However, we now have [Figma renders for what these components should look like](https://www.figma.com/file/IXAajiFoWwcPU70DFs6hRt/Site-Architecture?type=design&node-id=0%3A1&mode=design&t=U8QbdrdOGxMWu3xO-1). Here is a screenshot of the Figma (as of 11/04) but reference the actual Figma design (linked above) in case there has been changes.

![Image](https://github.com/CruzHacks/cruzhacks-2024-website/assets/20495250/ce03aab4-a36a-4451-971f-d2b8907aa846)

In addition to what is displayed, there should be error messages for the individual form entries and for the form submission as already provided in the code. Either confer with Ria from design or use your discretion for how this errors should be styled (my intuition says that form entries with errors should change to red and maybe have a red background).

## TODO:

*NOTE: I started the login page to give some reference on how to use tailwind and how the styles are references; refer to the tailwind.config.cjs to see all available colors and fonts*

- [x] Style Login Page
    - [x] Style fonts
    - [ ] Style form inputs
    - [ ] Style login button
    - [ ] Style error states / error messages
- [ ] Style Signup Page
    - [ ]  Style fonts
    - [ ] Style form inputs
    - [ ] Style ogin button
    - [ ] Style error states / error messages
