### ISSUE TITLE
Create Hacker Application Judging Portal

### ISSUE THREAD

**Issue by zacktraczyk** [CruzHacks/cruzhacks-2024-website#7]
# Scope

*Note: We do not have Figma mockups (or a thought out user flow) for this so it will take some creativity / foreplanning to think through a good dashboard as well as implement it*

After Hackers submit their applications, we need somewhere that us organizers can review them and approve or deny. Since this is only for us organizers it does not need to be super pretty but it should work. I am thinking it should have the following features:

## Possible Features:

- View Hacker Applications
    - Sort by judged and yet to be judged
    - Search by email or name if possible
    - Sort applications by different criteria (if possible)
- Judge applications
    - ~~approve applicant~~
        - ~~create a collection in Firestore (i.e. `applicant_decisions`) that has a doc (i.e. `approved`) with a list of approved emails~~
        - ~~transfer `user_role` from applicant account to hacker account~~
    - ~~deny applicant~~
        - ~~add to Firestore collection (i.e. `applicant_decisions`) that has a doc (i.e. `denied`) with a list of denied emails~~

**UPDATE 11/21:**

I'm thinking instead of making a collection like `applicant_decisions` we will just query all applications by `status` using a [group collection query](https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query). This means we will not need a new collection just to hold application decisions.

This means in the future we will need to create a Firestore Index to perform this query but it is super simple to set these up.

## TODO:

- [x] Think through Applicant Judging Dashboard
- [x] Confer with Zack / Ria about plan and where to put into admin dashboard
- [x] Create accept / reject buttons
- [x] Create accept / reject functions (or singular function) in `utils/apis/firebase.ts`
- [ ] Wrap accept / reject function/s in [React Query useMutation Hook](https://tanstack.com/query/v4/docs/react/guides/mutations), invalidate/mutate `useApplication` and `useApplications` hooks

### Optional but helpful TODOS:
- [ ] Create sort buttons in the column headers of the applications table using [React Query Select property](https://tanstack.com/query/v4/docs/react/reference/useQuery) in the `useApplications` hook
- [ ] Add pagination (in table rendering, in React Query `useApplications` hook, and in Firestore query)
